package p8499.style.core;

/**
 * Created by Administrator on 3/4/2018.
 */
public class Dimension {
    public static final String PERCENT_100 = "100%";
    public static final String PERCENT_090 = "90%";
    public static final String PERCENT_080 = "80%";
    public static final String PERCENT_070 = "70%";
    public static final String PERCENT_060 = "60%";
    public static final String PERCENT_050 = "50%";
    public static final String PERCENT_040 = "40%";
    public static final String PERCENT_030 = "30%";
    public static final String PERCENT_020 = "20%";
    public static final String PERCENT_010 = "10%";
    public static final String PERCENT_000 = "0%";
    public static final String SIZE_A = "56dp";
    public static final String SIZE_B = "52dp";
    public static final String SIZE_C = "48dp";
    public static final String SIZE_D = "44dp";
    public static final String SIZE_E = "40dp";
    public static final String SIZE_F = "36dp";
    public static final String SIZE_G = "32dp";
    public static final String SIZE_H = "28dp";
    public static final String SIZE_I = "24dp";
    public static final String SIZE_J = "20dp";
    public static final String SIZE_K = "16dp";
    public static final String DP_00 = "0dp";
    public static final String DP_00H = "0.5dp";
    public static final String DP_01 = "1dp";
    public static final String DP_01H = "1.5dp";
    public static final String DP_02 = "2dp";
    public static final String DP_02H = "2.5dp";
    public static final String DP_03 = "3dp";
    public static final String DP_04 = "4dp";
    public static final String DP_05 = "5dp";
    public static final String DP_06 = "6dp";
    public static final String DP_07 = "7dp";
    public static final String DP_08 = "8dp";
    public static final String DP_09 = "9dp";
    public static final String DP_10 = "10dp";
    public static final String DP_11 = "11dp";
    public static final String DP_12 = "12dp";
    public static final String DP_13 = "13dp";
    public static final String DP_14 = "14dp";
    public static final String DP_15 = "15dp";
    public static final String DP_16 = "16dp";
    public static final String TEXTSIZE_A = "28sp";
    public static final String TEXTSIZE_B = "26sp";
    public static final String TEXTSIZE_C = "24sp";
    public static final String TEXTSIZE_D = "22sp";
    public static final String TEXTSIZE_E = "20sp";
    public static final String TEXTSIZE_F = "18sp";
    public static final String TEXTSIZE_G = "16sp";
    public static final String TEXTSIZE_H = "14sp";
    public static final String TEXTSIZE_I = "12sp";
    public static final String TEXTSIZE_J = "10sp";
    public static final String TEXTSIZE_K = "8sp";
    public static final String TEXTPADDING_A = "7.4dp";
    public static final String TEXTPADDING_B = "7.3dp";
    public static final String TEXTPADDING_C = "7.2dp";
    public static final String TEXTPADDING_D = "7.1dp";
    public static final String TEXTPADDING_E = "7.0dp";
    public static final String TEXTPADDING_F = "6.9dp";
    public static final String TEXTPADDING_G = "6.8dp";
    public static final String TEXTPADDING_H = "6.7dp";
    public static final String TEXTPADDING_I = "6.6dp";
    public static final String TEXTPADDING_J = "6.5dp";
    public static final String TEXTPADDING_K = "6.4dp";
}
